import 'package:fcai_gpt/features/courses/data/course.dart';

class Cousres {
  static List<Course> courses = [
    Course('Advanced Data Structures', 3, ['Data structures']),
    Course('Concepts of Programming Languages', 3, ['Advanced Data Structures']),
    Course('Computer Organization and Architecture', 3, ['Data Structures', 'Logic Design']),
    Course('Advanced Operating Systems', 3, ['Operating Systems']),
    Course('Advanced Software Engineering', 3, ['Introduction to Software Engineering']),
    Course('Artificial Intelligence', 3, ['Data Structures']),
    Course('High Performance Computing', 3, ['Operating Systems']),
    Course('Information Theory and Data Compression', 3, ['Math-3', 'Object Oriented Programming']),
    Course('Computer Graphics', 3, ['Structured Programming']),
    Course('Compilers', 3, ['Concepts of Programming Languages']),
    Course('Computation Theory', 3, ['Discrete Math', 'Math-3']),
    Course('Machine Learning', 3, ['Probability and Statistics-1', 'Math-3', 'Object Oriented Programming']),
    Course('Cloud computing', 3, ['Advanced Operating Systems']),
    Course('Big Data Analysis', 3, ['Introduction to Database Systems', 'Machine learning']),
    Course('Bioinformatics Systems', 3, ['Algorithms Analysis and Design']),
    Course('Mobile Computing', 3, ['Operating Systems']),
    Course('Software Testing and Quality Assurance', 3, ['Algorithms Analysis and Design', 'Advanced Software Engineering']),
    Course('Software Security', 3, ['Algorithms Analysis and Design', 'Advanced Software Engineering']),
    Course('Human Computer Interaction', 3, ['Algorithms Analysis and Design', 'Advanced Software Engineering']),
    Course('Software Design and Architecture', 3, ['Algorithms Analysis and Design', 'Advanced Software Engineering']),
    Course('Selected Topics in Software Engineering', 3, ['Advanced Software Engineering']),
    Course('Natural Language Processing', 3, ['Machine Learning']),
    Course('Semantic Web and Ontology', 3, ['Artificial Intelligence', 'Web technology']),
    Course('Soft Computing', 3, ['Probability and Statistics-1', 'Math-2']),
    Course('Knowledge Discovery', 3, ['Introduction to Database Systems', 'Artificial Intelligence']),
    Course('Selected Topics in Artificial Intelligence', 3, ['Machine Learning']),
    Course('Advanced High Performance Computing', 3, ['High Performance Computing', 'Advanced Operating Systems']),
    Course('Selected Topics in High Performance Computing', 3, ['Advanced High Performance Computing']),
    Course('Selected Topics in Computer Science-1', 3, ['Concepts of Programming Languages']),
    Course('Selected Topics in Computer Science-2', 3, ['Concepts of Programming Languages']),
    Course('Database Management Systems', 3, ['Introduction to Database Systems', 'Object-Oriented Programming']),
    Course('Data Warehousing', 3, ['Introduction to Database Systems']),
    Course('File Management and Processing', 3, ['Data Structures']),
    Course('Information Retrieval', 3, ['Introduction to Database Systems', 'Probability and Statistics-2']),
    Course('Analysis and Design of Information Systems', 3, ['Introduction to Database Systems']),
    Course('Web-based Information Systems Development', 3, ['Web Technology']),
    Course('Business Process Management', 3, ['Analysis and Design of Information Systems']),
    Course('Artificial Intelligence', 3, ['Data structures']),
    Course('Managing and Modeling Big Data', 3, ['Database Management Systems']),
    Course('Data Mining', 3, ['Information Retrieval']),
    Course('Service-Oriented Architecture', 3, ['Web-based Information Systems Development']),
    Course('Fundamentals of Information Systems', 3, ['Introduction to Database Systems']),
    Course('Cloud Database', 3, [': Database Management Systems']),
    Course('Distributed Database', 3, ['Database Management Systems']),
    Course('Selected Topics in Database', 3, ['Database Management Systems']),
    Course('Business Process Mining', 3, ['Business Process Management']),
    Course('Selected Topics in Data Engineering', 3, ['Database Management Systems']),
    Course('Usability Engineering', 3, ['Web Technology']),
    Course('Enterprise Mobile Applications Development', 3, ['Web Technology']),
    Course('Information Systems Development Methodologies', 3, ['Analysis and Design of Information Systems']),
    Course('Management Information Systems', 3, ['Analysis and Design of Information Systems']),
    Course('Selected Topics in Advanced Information Systems', 3, ['Selected Topics in Advanced Information Systems']),
    Course('Geographical Information Systems', 3, ['Database Management Systems']),
    Course('Information Systems Quality Assurance', 3, ['Information Systems Quality Assurance']),
    Course('Information Systems Security and Risk Management', 3, ['Analysis and Design of Information Systems']),
    Course('Information Systems Audit and Control', 3, ['Analysis and Design of Information Systems']),
    Course('Enterprise Information Systems', 3, ['Web-based', 'Information Systems Development']),
    Course('Information Systems Project management', 3, ['Analysis and Design of Information Systems']),
    Course('E-Business', 3, ['Analysis and Design of Information Systems']),
    Course('Selected Topics in Information Systems Engineering', 3, ['Web-based', 'Information Systems Development']),
    Course('Selected Topics in Information Systems-1', 3, ['Analysis and Design of Information Systems']),
    Course('Selected Topics in Information Systems-2', 3, ['Analysis and Design of Information Systems']),
    Course('Introduction to Logic', 3, ['Discrete Mathematics', 'Probability and Statistics-2']),
    Course('Reasoning and Knowledge Representation', 3, ['Introduction to Logic']),
    Course('Processing Formal and Natural Languages', 3, ['Introduction to Logic']),
    Course('Autonomous Multiagent Systems', 3, ['Introduction to Logic']),
    Course('Theoretical Foundations of Machine Learning', 3, ['Math-3', 'Probability and Statistics-2']),
    Course('Supervised Learning', 3, ['Theoretical Foundations of Machine Learning']),
    Course('Unsupervised Learning', 3, ['Theoretical Foundations of Machine Learning']),
    Course('Theories of Mind', 3, ['Discrete Mathematic']),
    Course('Computational Cognitive Science', 3, ['Introduction to Logic']),
    Course('Reinforcement Learning', 3, ['Supervised Learning']),
    Course('Intelligent Autonomous Robotics', 3, ['Supervised Learning']),
    Course('Cognitive Robotics', 3, ['Supervised Learning', 'Intelligent Autonomous Robotics']),
    Course('Generative Adversarial Networks', 3, ['Supervised Learning']),
    Course('Fundamentals of Biometric Identification', 3, ['Supervised Learning']),
    Course('Brain-Computer Interfacing', 3, ['Supervised Learning']),
    Course('Principles of Quantum Artificial Intelligence', 3, ['Theoretical Foundations of Machine Learning']),
    Course('Business Intelligence: Strategies, Tools & Techniques', 3, ['Theoretical Foundations of Machine Learning']),
    Course('Artificial Intelligence for Cybersecurity', 3, ['Supervised Learning', 'Computer Networks Technology']),
    Course('Selected Topics in Artificial Intelligence-1', 3, ['Student must have passed 60 Credit Hours']),
    Course('Selected Topics in Artificial Intelligence-2', 3, ['Student must have passed 60 Credit Hours']),
    Course('Technical Report Writing', 2, []),
    Course('Ethics and professionalism', 2, []),
    Course('Creative Thinking and Communication', 2, []),
    Course('Fundamentals of Economies', 2, []),
    Course('Fundamentals of Management', 2, []),
    Course('Marketing and Sales', 2, []),
    Course('Fundamentals of Psychology', 2, []),
    Course('Fundamentals of Sociology', 2, []),
    Course('Comparative Politics', 2, []),
    Course('Human Rights', 2, []),
    Course('Selected Topics in Humanities', 2, []),
    Course('Math-1', 3, []),
    Course('Discrete Mathematics', 3, ['Math-1']),
    Course('Math-2', 3, ['Math-1']),
    Course('Electronics', 3, []),
    Course('Math-3', 3, ['Math-2']),
    Course('Probability and Statistics-1', 3, ['Math-1']),
    Course('Probability and Statistics-2', 3, ['Probability and Statistics-1']),
    Course('Fundamentals of Computer Science', 3, []),
    Course('Structured Programming', 3, ['Fundamentals of Computer Science']),
    Course('Object Oriented Programming', 3, ['Structured Programming']),
    Course('Data Structures', 3, ['Object Oriented Programming']),
    Course('Introduction to Software Engineering', 3, ['Structured Programming']),
    Course('Introduction to Operations Research and Decision Support', 3, ['Probability and Statistics-1']),
    Course('Introduction to Database Systems', 3, ['Structured Programming']),
    Course('Web Technology', 3, ['Object Oriented Programming']),
    Course('Logic Design', 3, ['Electronics']),
    Course('Computer Networks Technology', 3, ['Fundamentals of Computer Science']),
    Course('Algorithms Analysis and Design', 3, ['Data Structures']),
    Course('Operating Systems', 3, ['Data Structures']),
    Course('Decision Support and Future Studies Methodologies', 3, ['Introduction to Operations Research', 'Decision Support']),
    Course('Computational Intelligence', 3, ['Linear and Integer Programming', 'Probability and Statistics-2']),
    Course('Linear and Integer Programming', 3, ['Math-2', 'Introduction to Operations Research', 'Decision Support']),
    Course('Non Linear Programming', 3, ['Linear and Integer Programming']),
    Course('Dynamic Programming and Stochastic Modeling', 3, ['Linear and Integer Programming']),
    Course('System Modeling and Simulation', 3, ['Object Oriented Programming']),
    Course('Learning From Data', 3, ['Probability and Statistics-2']),
    Course('Production and Operations Management', 3, ['Decision Support', 'Future Studies Methodologies']),
    Course('Game Theory', 3, ['Probability and Statistics-2', 'Linear and Integer Programming']),
    Course('Decision Theory', 3, ['Probability and Statistics-2', 'Linear and Integer Programming']),
    Course('Multi-objective Programming', 3, ['Non-Linear Programming']),
    Course('Network Modeling and Optimization', 3, ['Dynamic Programming', 'Stochastic Modeling']),
    Course('Data Analytics', 3, ['Probability and Statistics-2']),
    Course('Probabilistic Reasoning', 3, ['Probability and Statistics-2']),
    Course('Forecasting and Predictive Analytics', 3, ['Learning From Data']),
    Course('Strategic Decision Making', 3, ['Linear and Integer Programming']),
    Course('System Dynamics Modeling', 3, ['System Modeling', 'Simulation']),
    Course('Agent-Based Modeling and Complex Systems', 3, ['System Modeling', 'Simulation']),
    Course('Crisis Management', 3, ['Decision Support', 'Future Studies Methodologies']),
    Course('Service Management', 3, ['Decision Support', 'Future Studies Methodologies']),
    Course('Managerial Economics and Financial Analysis', 3, ['Decision Support', 'Future Studies Methodologies']),
    Course('Project Management', 3, ['Introduction to Operations Research', 'Decision Support']),
    Course('Selected Topics in Operations Research and Decision Support-1', 3, ['Completion of 60 credit hours']),
    Course('Selected Topics in Operations Research and Decision Support-2', 3, ['Completion of 60 credit hours']),
    Course('Computer Architecture', 3, ['Logic Design']),
    Course('Micro Controllers', 3, ['Logic Design']),
    Course('Advanced Computer Networks', 3, ['Computer Networks Technology', 'Data Communication']),
    Course('Data Communication', 3, ['Math-2']),
    Course('Signals and Systems', 3, ['Math-3']),
    Course('Digital Signal Processing', 3, ['Signals and Systems']),
    Course('Pattern Recognition', 3, ['Signals and Systems', 'Probability and Statistics-2']),
    Course('Information and Computer Networks Security', 3, ['Advanced Computer Networks Technology']),
    Course('Communication Technology', 3, ['Computer Networks Technology']),
    Course('Image Processing', 3, ['Signals and Systems']),
    Course('Multimedia Mining', 3, ['Pattern Recognition']),
    Course('Machine Vision', 3, ['Image Processing', 'Computer Graphics']),
    Course('Robotics', 3, ['Micro Controllers']),
    Course('Embedded System', 3, ['Micro Controllers']),
    Course('Selected Topics in Embedded Systems and Robotic', 3, ['Micro Controllers']),
    Course('Wireless and Mobile Networks', 3, ['Advanced Computer Networks']),
    Course('Cloud Computing Networks', 3, ['Advanced Computer Networks']),
    Course('Internet Programming and Protocols', 3, ['Advanced Computer Networks']),
    Course('Optical Networks', 3, ['Advanced Computer Networks']),
    Course('Wireless Sensors Networks', 3, ['Wireless and Mobile Networks']),
    Course('Selected Topics in Computer Networks', 3, ['Advanced Computer Networks']),
    Course('Cyber Security', 3, ['Information and Computer Networks Security']),
    Course('Advanced Image Processing', 3, ['Image Processing']),
    Course('Virtual Reality', 3, ['Image Processing', 'Computer Graphics']),
    Course('Speech Processing', 3, ['Digital Signal Processing']),
    Course('Selected Topics in Multimedia', 3, ['Pattern Recognition']),
    Course('Advanced Pattern Recognition', 3, ['Pattern Recognition']),
    Course('Human Language Technology', 3, ['Pattern Recognition']),
    Course('Advanced Computer Graphics', 3, ['Computer Graphics']),
    Course('Computer Animation', 3, ['Computer Graphics']),
    Course('Ubiquitous Computing', 3, ['Advanced Computer Networks', 'Structured Programming']),
    Course('Concurrency and Parallel Computing', 3, ['Computer Architecture', 'Structured Programming']),
    Course('Intelligent and Quantum Computing', 3, ['Computer Architecture', 'Data Structures']),
  ];
}
