// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmo3lCFah54mnUMk7HZPzoTs-JWdL8YvU',
    appId: '1:885445644447:web:f078c37c4e0d4a230b92aa',
    messagingSenderId: '885445644447',
    projectId: 'fcai-gpt',
    authDomain: 'fcai-gpt.firebaseapp.com',
    storageBucket: 'fcai-gpt.appspot.com',
    measurementId: 'G-9RBXMJKPTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8gQov6QUfHLdjmN13PHeYWhCoD3XtcU',
    appId: '1:885445644447:android:99dd4227462d64020b92aa',
    messagingSenderId: '885445644447',
    projectId: 'fcai-gpt',
    storageBucket: 'fcai-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCij0E7YZ7Hlof-Assb-XGWDh_zDcrb8g8',
    appId: '1:885445644447:ios:b434e32cb86bf97d0b92aa',
    messagingSenderId: '885445644447',
    projectId: 'fcai-gpt',
    storageBucket: 'fcai-gpt.appspot.com',
    iosBundleId: 'com.example.fcaiGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCij0E7YZ7Hlof-Assb-XGWDh_zDcrb8g8',
    appId: '1:885445644447:ios:cbbb47e60a575ad20b92aa',
    messagingSenderId: '885445644447',
    projectId: 'fcai-gpt',
    storageBucket: 'fcai-gpt.appspot.com',
    iosBundleId: 'com.example.fcaiGpt.RunnerTests',
  );
}
